<?php

namespace QCM\BackBundle\Repository;

/**
 * QuestionTirageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionTirageRepository extends \Doctrine\ORM\EntityRepository
{
}
