<?php

namespace QCM\BackBundle\Repository;

/**
 * ReponseProposeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseProposeeRepository extends \Doctrine\ORM\EntityRepository
{
}
