<?php

namespace QCM\BackBundle\Repository;

/**
 * ReponseDonneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseDonneeRepository extends \Doctrine\ORM\EntityRepository
{
}
