<?php

namespace QCM\BackBundle\Repository;

/**
 * SectionTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionTestRepository extends \Doctrine\ORM\EntityRepository
{
}
