<?php

namespace QCM\BackBundle\Repository;

/**
 * SimpleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SimpleRepository extends \Doctrine\ORM\EntityRepository
{
}
