<?php

namespace QCM\BackBundle\Repository;

/**
 * StaffENIRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffENIRepository extends \Doctrine\ORM\EntityRepository
{
}
